### ISSUE TITLE
Quill support

### ISSUE THREAD

**Issue by KyooMario** [Weavy/quill-autoformat#1]
Hello Weavy,

I came across your Quill addon and want to ask if you are willing to help me with some other customizations.
I tried to do some customizations myself but get stuck on build issues when I try to use the github source. Target platform is plain javascript.

Hope you can help.
Kind regards,
Mario

**Comment by klasjersevi** [comment]
Hi Mario! Make sure you use the latest Node if you run in to build problems. I'll see if I can specify Node version in the package. Hope that helps!
