### ISSUE TITLE
npm i quill-autoformat fails

### ISSUE THREAD

**Issue by matthieu-hm** [Weavy/quill-autoformat#2]
npm can't find "quill": "2.0.0-dev.2"

To fix this you can change quill version to "2.0.0-dev.3" or remove it from dependencies and only write the installation commands in the README.md

Personnaly I think the second way is better because if quill make an other release you won't need to update package.json again

**Comment by klasjersevi** [comment]
Thank you for taking notice. I've updated the dependencies and made a new release. If you use npm instead of yarn, you might run into some unexpected problems as this is only tested with yarn.
