### ISSUE TITLE
Use with vue-quill-editor

### ISSUE THREAD

**Issue by ghost** [Weavy/quill-autoformat#4]
I am struggling a lot getting this plugin to work with https://github.com/surmon-china/vue-quill-editor.

The problem comes down to:
```
Uncaught Error: [Parchment] Unable to create hashtag blot
    at new ParchmentError (quill.js?9339:148)
```
This error comes up upon typing a hashtag. Any idea?

**Comment by klasjersevi** [comment]
Yes, vue-quill-editor uses Quill 1.3.4 while this is made for Quill 2.0.0-dev.3.

**Comment by ghost** [comment]
Too bad, any idea which calls need to be adjusted to make it work with the current production version of quill?
I already found that `new Attributor()` should be `new Attributor.Attribute()`, this brings me a step closer. The blot error as above still persists.

**Comment by ghost** [comment]
Nevermind. Instead trying to downgrade your work, I decided to actually fork `vue-quill-editor` and upgrade it. 

For reference: This can be found here
https://www.npmjs.com/package/@voicehub/vue-quill-editor
https://github.com/voicehub-io/vue-quill-editor
